/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java_MysqlConn;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class Java_MysqlConn extends javax.swing.JFrame {

  private static final String username="root";
  private static final String password="system";
  private static final String dataConn="jdbc:mysql://localhost:3306/connector"; // database name
  
  
  Connection sqlConn=null;
  PreparedStatement pst=null;
  ResultSet rs=null;
  int q, i, id, deleteItem;
  
  
    public Java_MysqlConn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //================== Function =====================================
    
    public void upDateDB() 
    {
        try{
          Class.forName("com.mysql.jdbc.Driver");
          sqlConn=DriverManager.getConnection(dataConn, username, password);
          pst=sqlConn.prepareStatement("select * from connector");
          
          
          rs=pst.executeQuery();
          ResultSetMetaData stData=rs.getMetaData();
          
          q=stData.getColumnCount();
          
          DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
          RecordTable.setRowCount(0);
          
          while(rs.next()){
              Vector columnData = new Vector();
              for(i=1; i<=q;i++){
                  columnData.add(rs.getString("id"));
                  columnData.add(rs.getString("StudentID"));
                  columnData.add(rs.getString("Firstname"));
                  columnData.add(rs.getString("Surname"));
                  columnData.add(rs.getString("Address"));
                  columnData.add(rs.getString("PostCode"));
                  columnData.add(rs.getString("Telephone"));
                  
                  
                     
              }
               RecordTable.addRow(columnData);
          }
          
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtxtTelephone = new javax.swing.JTextField();
        g4tgt = new javax.swing.JLabel();
        gtgg = new javax.swing.JLabel();
        gtrgr = new javax.swing.JLabel();
        gegtrtg = new javax.swing.JLabel();
        rtgrgt = new javax.swing.JLabel();
        trgrgr = new javax.swing.JLabel();
        jtxtStudentID = new javax.swing.JTextField();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtPostcode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtdelete = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jbtexit = new javax.swing.JButton();
        jbtadd = new javax.swing.JButton();
        jbtupdate = new javax.swing.JButton();
        jbtprint = new javax.swing.JButton();
        jbtreset = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 8));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 8));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 8));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 180, 410));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 8));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 8));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 180, 410));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 180, 410));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 180, 410));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTelephone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTelephoneActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 370, -1));

        g4tgt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        g4tgt.setText("Student ID");
        jPanel2.add(g4tgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        gtgg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gtgg.setText("Firstname");
        jPanel2.add(gtgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        gtrgr.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gtrgr.setText("Surname");
        jPanel2.add(gtrgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        gegtrtg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gegtrtg.setText("Address");
        jPanel2.add(gegtrtg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        rtgrgt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rtgrgt.setText("Post Code");
        jPanel2.add(rtgrgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        trgrgr.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        trgrgr.setText("Telephone ");
        jPanel2.add(trgrgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jtxtStudentID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStudentIDActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 370, -1));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstnameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 370, -1));

        jtxtSurname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSurnameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 370, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 370, -1));

        jtxtPostcode.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jtxtPostcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 370, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Student ID", "Firstname", "Surname", "Address", "Post Code", "Telephone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 950, 390));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 980, 750));

        jbtdelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 8));
        jbtdelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 8));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jbtdelete.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 180, 410));

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 8));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 8));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 180, 410));

        jbtdelete.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 180, 410));

        jbtexit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbtexit.setText("Exit");
        jbtexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtexitActionPerformed(evt);
            }
        });
        jbtdelete.add(jbtexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 170, 50));

        jbtadd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbtadd.setText("Add new data");
        jbtadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtaddActionPerformed(evt);
            }
        });
        jbtdelete.add(jbtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 170, 50));

        jbtupdate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbtupdate.setText("Update");
        jbtupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtupdateActionPerformed(evt);
            }
        });
        jbtdelete.add(jbtupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 170, 50));

        jbtprint.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbtprint.setText("Print");
        jbtprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtprintActionPerformed(evt);
            }
        });
        jbtdelete.add(jbtprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 170, 50));

        jbtreset.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbtreset.setText("Reset");
        jbtreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtresetActionPerformed(evt);
            }
        });
        jbtdelete.add(jbtreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 170, 50));

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jbtdelete.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 170, 50));

        jPanel1.add(jbtdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 280, 750));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel1.setText("My SQL Connection");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 770, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 1280, 860));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        
private JFrame frame;
    private void jbtexitActionPerformed(java.awt.event.ActionEvent evt) {                                        


        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit: ", "Student Result System System ",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        


    }                                       

    private void jbtresetActionPerformed(java.awt.event.ActionEvent evt) {                                         

   
jtxtTelephone.setText(" ");
jtxtSurname.setText("");
jtxtFirstname.setText("");
jtxtAddress.setText("");
jtxtStudentID.setText("");
jtxtPostcode.setText("");







    }                                        

    private void jbtaddActionPerformed(java.awt.event.ActionEvent evt) {                                       

        try{
          Class.forName("com.mysql.jdbc.Driver");
          sqlConn=DriverManager.getConnection(dataConn, username, password);
          pst=sqlConn.prepareStatement("insert into connector(StudentID, Firstname, Surname, Address,"
                  + "PostCode, Telephone) value(?, ?, ?, ?, ?, ?)");
        
        pst.setString(1,jtxtStudentID.getText());
        pst.setString(2,jtxtFirstname.getText());
        pst.setString(3,jtxtSurname.getText());
        pst.setString(4,jtxtAddress.getText());
        pst.setString(5,jtxtPostcode.getText());
        pst.setString(6,jtxtTelephone.getText());
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this,"Record Added");
        upDateDB();
        
        
        }
        
        catch(ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        }
        catch(SQLException ex){
         java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        // TODO add your handling code here:
    }                                      

    private void jtxtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jbtupdateActionPerformed(java.awt.event.ActionEvent evt) {                                          

try{
          Class.forName("com.mysql.jdbc.Driver");
          sqlConn=DriverManager.getConnection(dataConn, username, password);
          int i= Integer.parseInt( JOptionPane.showInputDialog("Which id do you want to update? "));
          pst=sqlConn.prepareStatement("update connector set StudentID=?, Firstname=?, Surname=?, Address=?, PostCode=?, Telephone=? where id=?");
        
        pst.setString(1,jtxtStudentID.getText());
        pst.setString(2,jtxtFirstname.getText());
        pst.setString(3,jtxtSurname.getText());
        pst.setString(4,jtxtAddress.getText());
        pst.setString(5,jtxtPostcode.getText());
        pst.setString(6,jtxtTelephone.getText());
        pst.setInt(7,id);
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this,"Record Updated");
        upDateDB();
        
        
        }
        
        catch(ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        }
        catch(SQLException ex){
         java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

    }                                         

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     

// this is the mouse clicked event. When you click ysing the mouse the records will be displayed in the empty spaces

       DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
      int SelectedRows= jTable1.getSelectedRow();  // you select the row from the table 
      
      
      jtxtStudentID.setText(RecordTable.getValueAt(SelectedRows, 1).toString()); // this is for the student id
      jtxtFirstname.setText(RecordTable.getValueAt(SelectedRows, 2).toString()); // this is for the student id
      jtxtSurname.setText(RecordTable.getValueAt(SelectedRows, 3).toString()); // this is for the student id
      jtxtAddress.setText(RecordTable.getValueAt(SelectedRows, 4).toString()); // this is for the student id
      jtxtPostcode.setText(RecordTable.getValueAt(SelectedRows, 5).toString()); // this is for the student id
      jtxtTelephone.setText(RecordTable.getValueAt(SelectedRows, 6).toString()); // this is for the student id
      

      
    }                                    

    private void jtxtSurnameActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jbtprintActionPerformed(java.awt.event.ActionEvent evt) {                                         

MessageFormat header=new MessageFormat("Printing in Progress");
MessageFormat footer=new MessageFormat("Page {0, number, integer}");

try{
    jTable1.print(JTable.PrintMode.NORMAL, header, footer);
    
}
catch(java.awt.print.PrinterException e){
    System.err.format("No printer found", e.getMessage());
}



        // TODO add your handling code here:
    }                                        

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          

// Delete

 DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
      int SelectedRows= jTable1.getSelectedRow();
      
      try{
          id=Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
          deleteItem=JOptionPane.showConfirmDialog(null, " Confirm if you want to delete the item",
                  "Warning", JOptionPane.YES_NO_OPTION);
          if(deleteItem==JOptionPane.YES_OPTION)
          {
              Class.forName("com.mysql.jdbc.Driver");
              sqlConn=DriverManager.getConnection(dataConn, username, password);
              pst=sqlConn.prepareStatement("delete from connector where id=?");
              
              pst.setInt(1, id);
              pst.executeUpdate();
              JOptionPane.showMessageDialog(this, "Students record updated");
              
              upDateDB();
              
                 
            jtxtTelephone.setText(" ");
            jtxtSurname.setText("");
            jtxtFirstname.setText("");
            jtxtAddress.setText("");
            jtxtStudentID.setText("");
            jtxtPostcode.setText("");
              
              
              
              
              
          }
      }
      
      catch(ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        }
        catch(SQLException ex){
         java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }




        // TODO add your handling code here:
    }                                         

    private void jtxtTelephoneActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jtxtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Java_MysqlConn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel g4tgt;
    private javax.swing.JLabel gegtrtg;
    private javax.swing.JLabel gtgg;
    private javax.swing.JLabel gtrgr;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtadd;
    private javax.swing.JPanel jbtdelete;
    private javax.swing.JButton jbtexit;
    private javax.swing.JButton jbtprint;
    private javax.swing.JButton jbtreset;
    private javax.swing.JButton jbtupdate;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtPostcode;
    private javax.swing.JTextField jtxtStudentID;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtTelephone;
    private javax.swing.JLabel rtgrgt;
    private javax.swing.JLabel trgrgr;
    // End of variables declaration                   
}
